# Configuración de Supabase

[supabase]
url = "https://lxsxxgaudhliaoerewmp.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4c3h4Z2F1ZGhsaWFvZXJld21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2NjA1NjEsImV4cCI6MjA0OTIzNjU2MX0.F8y5gGcsx6e4TS-Ce1SIq0sbkEBuvLzmGr8qCPeq8rw"